export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const FETCHING = 'FETCHING';
export const GET_HOME_SUCCESS = 'GET_HOME_SUCCESS';

export const CREATE_TOPIC = 'CREATE_TOPIC';
export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_FICTION_SUCCESS = 'GET_FICTION_SUCCESS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';

// EDITOR
export const CHOOSE_POSITION = 'CHOOSE_POSITION';
export const GET_EDITOR_CHOOSE_PARENT_SUCCESS = 'GET_EDITOR_CHOOSE_PARENT_SUCCESS';
export const GET_SUBMIT_SUCCESS = 'GET_SUBMIT_SUCCESS';
export const CHOOSE_SCHEDULE_TYPE = 'CHOOSE_SCHEDULE_TYPE';
export const CHOOSE_VOLUME = 'CHOOSE_VOLUME';
export const OPEN_ADD_AUTHOR = 'OPEN_ADD_AUTHOR';
export const OPEN_CHOOSE_PARENT = 'OPEN_CHOOSE_PARENT';
export const OPEN_CHOOSE_VOLUME = 'OPEN_CHOOSE_VOLUME';
export const OPEN_SCHEDULE_TYPE = 'OPEN_SCHEDULE_TYPE';
export const POST_EDITOR_ADD_AUTHOR_SUCCESS = 'POST_EDITOR_ADD_AUTHOR_SUCCESS';
export const POST_EDITOR_SUBMIT_SUCCESS = 'POST_EDITOR_SUBMIT_SUCCESS';
export const REMOVE_AUTHOR = 'REMOVE_AUTHOR';
export const SELECTING = 'SELECTING';
export const SET_AUTOINDEX = 'SET_AUTOINDEX';
export const SET_DRAFT = 'SET_DRAFT';
export const SET_FOLLOWER_CHAPTER = 'SET_FOLLOWER_CHAPTER';
export const TYPING = 'TYPING';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

// CHAPTER
export const GET_CHAPTER_SUCCESS = 'GET_CHAPTER_SUCCESS';
export const POST_CHAPTER_DOWN_SUCCESS = 'POST_CHAPTER_DOWN_SUCCESS';
export const POST_CHAPTER_DOWN_REMOVE_SUCCESS = 'POST_CHAPTER_DOWN_REMOVE_SUCCESS';
export const POST_CHAPTER_SUCCESS = 'POST_CHAPTER_SUCCESS';
export const POST_CHAPTER_THANKS_SUCCESS = 'POST_CHAPTER_THANKS_SUCCESS';
export const POST_CHAPTER_THANKS_REMOVE_SUCCESS = 'POST_CHAPTER_THANKS_REMOVE_SUCCESS';
export const POST_CHAPTER_UP_SUCCESS = 'POST_CHAPTER_UP_SUCCESS';
export const POST_CHAPTER_UP_REMOVE_SUCCESS = 'POST_CHAPTER_UP_REMOVE_SUCCESS';
export const POST_CHAPTER_UPDATE_SUCCESS = 'POST_CHAPTER_UPDATE_SUCCESS';

// COMMENT
export const GET_COMMENT_COMMENTS_SUCCESS = 'GET_COMMENT_COMMENTS_SUCCESS';
export const GET_CONVERSATIONS_MORE_SUCCESS = 'GET_CONVERSATIONS_MORE_SUCCESS';
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATION_SUCCESS';
export const GET_CONVERSATION_MORE_MESSAGE_SUCCESS = 'GET_CONVERSATION_MORE_MESSAGE_SUCCESS';
export const GET_REVIEW_REVIEWS_SUCCESS = 'GET_REVIEW_REVIEWS_SUCCESS';
export const GET_COMMENT_REPLIES_SUCCESS = 'GET_COMMENT_REPLIES_SUCCESS';
export const GET_TYPO_TYPOS_SUCCESS = 'GET_TYPO_TYPOS_SUCCESS';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const EDIT_REVIEW = 'EDIT_REVIEW';
export const POST_COMMENT_CONFIRM_REPORT_FAILURE = 'POST_COMMENT_CONFIRM_REPORT_FAILURE';
export const POST_COMMENT_CONFIRM_REPORT_SUCCESS = 'POST_COMMENT_CONFIRM_REPORT_SUCCESS';
export const POST_COMMENT_DELETE_SUCCESS = 'POST_COMMENT_DELETE_SUCCESS';
export const POST_COMMENT_EDIT_SUCCESS = 'POST_COMMENT_EDIT_SUCCESS';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_DOWN_SUCCESS = 'POST_COMMENT_DOWN_SUCCESS';
export const POST_COMMENT_DOWN_REMOVE_SUCCESS = 'POST_COMMENT_DOWN_REMOVE_SUCCESS';
export const POST_COMMENT_UP_SUCCESS = 'POST_COMMENT_UP_SUCCESS';
export const POST_COMMENT_UP_REMOVE_SUCCESS = 'POST_COMMENT_UP_REMOVE_SUCCESS';
export const POST_CONVERSATION_DELETE_SUCCESS = 'POST_CONVERSATION_DELETE_SUCCESS';
export const POST_CONVERSATION_TRASH_SUCCESS = 'POST_CONVERSATION_TRASH_SUCCESS';
export const POST_CONVERSATION_UNTRASH_SUCCESS = 'POST_CONVERSATION_UNTRASH_SUCCESS';
export const POST_CONVERSATION_STAR_SUCCESS = 'POST_CONVERSATION_STAR_SUCCESS';
export const POST_CONVERSATION_UNSTAR_SUCCESS = 'POST_CONVERSATION_UNSTAR_SUCCESS';
export const POST_REVIEW_EDIT_SUCCESS = 'POST_REVIEW_EDIT_SUCCESS';
export const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';

// FICTION
export const GET_AUTHOR_WORKS_SUCCESS = 'GET_AUTHOR_WORKS_SUCCESS';
export const GET_FICTION_VOLUMES_SUCCESS = 'GET_FICTION_VOLUMES_SUCCESS';
export const GET_FICTION_VOLUME_SUCCESS = 'GET_FICTION_VOLUME_SUCCESS';
export const FICTION_CLOSE_VOLUMES = 'FICTION_CLOSE_VOLUMES';
export const GET_FICTION_COMMENTS_SUCCESS = 'GET_FICTION_COMMENTS_SUCCESS';
export const GET_FICTION_REVIEWS_SUCCESS = 'GET_FICTION_REVIEWS_SUCCESS';
export const GET_FICTION_TYPOS_SUCCESS = 'GET_FICTION_TYPOS_SUCCESS';
export const OPEN_RATE = 'OPEN_RATE';
export const POST_CONFIRM_RATE_SUCCESS = 'POST_CONFIRM_RATE_SUCCESS';
export const POST_FICTION_CONFIRM_DONATE_SUCCESS = 'POST_FICTION_CONFIRM_DONATE_SUCCESS';
export const POST_FICTION_CONFIRM_LIST_SUCCESS = 'POST_FICTION_CONFIRM_LIST_SUCCESS';
export const POST_FICTION_CONFIRM_SUBSCRIBED_SUCCESS = 'POST_FICTION_CONFIRM_SUBSCRIBED_SUCCESS';
export const POST_FICTION_DOWN_SUCCESS = 'POST_FICTION_DOWN_SUCCESS';
export const POST_FICTION_DOWN_REMOVE_SUCCESS = 'POST_FICTION_DOWN_REMOVE_SUCCESS';
export const POST_FICTION_FAVORITE_SUCCESS = 'POST_FICTION_FAVORITE_SUCCESS';
export const POST_FICTION_FAVORITE_REMOVE_SUCCESS = 'POST_FICTION_FAVORITE_REMOVE_SUCCESS';
export const POST_FICTION_FOLLOW_SUCCESS = 'POST_FICTION_FOLLOW_SUCCESS';
export const POST_FICTION_FOLLOW_REMOVE_SUCCESS = 'POST_FICTION_FOLLOW_REMOVE_SUCCESS';
export const POST_FICTION_CONFIRM_REPORT_FAILURE = 'POST_FICTION_CONFIRM_REPORT_FAILURE';
export const POST_FICTION_CONFIRM_REPORT_SUCCESS = 'POST_FICTION_CONFIRM_REPORT_SUCCESS';
export const POST_FICTION_UP_SUCCESS = 'POST_FICTION_UP_SUCCESS';
export const POST_FICTION_UP_REMOVE_SUCCESS = 'POST_FICTION_UP_REMOVE_SUCCESS';
export const POST_FICTION_UPDATE_SUCCESS = 'POST_FICTION_UPDATE_SUCCESS';

export const FICTION_EXPAND = 'FICTION_EXPAND';
export const GET_UNIVERSE_SUCCESS = 'GET_UNIVERSE_SUCCESS';
export const GET_LISTS_EXPAND_SUCCESS = 'GET_LISTS_EXPAND_SUCCESS';
export const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS';
export const LIST_ITEM_EXPAND = 'LIST_ITEM_EXPAND';
export const POST_LIST_DELETE_SUCCESS = 'POST_LIST_DELETE_SUCCESS';

export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const POST_LIST_DELETE_ITEM_SUCCESS = 'POST_LIST_DELETE_ITEM_SUCCESS';

// USER
export const GET_USER_EXPAND_FRIENDS_SUCCESS = 'GET_USER_EXPAND_FRIENDS_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_MORE_WORKS_SUCCESS = 'GET_MORE_WORKS_SUCCESS';
export const GET_WORKS_SUCCESS = 'GET_WORKS_SUCCESS';
export const POST_USER_ADD_FRIEND_SUCCESS = 'POST_USER_ADD_FRIEND_SUCCESS';
export const POST_USER_REMOVE_FRIEND_SUCCESS = 'POST_USER_REMOVE_FRIEND_SUCCESS';

// DASHBOARD
export const DASHBOARD_STAT_CHOOSE = 'DASHBOARD_STAT_CHOOSE';
export const DASHBOARD_STAT_TAB = 'DASHBOARD_STAT_TAB';
export const DASHBOARD_STAT_CHOOSE_CONFIRM = 'DASHBOARD_STAT_CHOOSE_CONFIRM';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const HIDE_STATS = 'HIDE_STATS';
export const SHOW_STATS = 'SHOW_STATS';

// POPUP
export const CLOSE_POPUP = 'CLOSE_POPUP';
export const POPUP_RATE_REVIEW = 'POPUP_RATE_REVIEW';

// NOTIFICATIONS
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';

// Navigation
export const NAVIGATION_ADD = 'NAVIGATION_ADD';
export const SEARCH_TYPING = 'SEARCH_TYPING';
export const SET_SEARCH_OPTIONS = 'SET_SEARCH_OPTIONS';
export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';